### ISSUE TITLE
WiresharkOuiService down

### ISSUE THREAD

**Issue by rm3l** [rm3l/mac-oui#318]
`WiresharkOuiService` does not seem to be able to download the OUI list.

```
$ ./gradlew quarkusDev

__  ____  __  _____   ___  __ ____  ______                                                                                                                                                     
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/                                                                                                                                                     
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \                                                                                                                                                       
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/                                                                                                                                                       
2023-09-19 23:00:51,294 INFO  [org.rm3.mac.ser.MacOuiService] (Quarkus Main Thread) Updating local database using 1 RemoteMacOuiServiceClient(s)...                                            
     2023-09-19 23:00:51,866 WARN  [org.rm3.mac.ser.MacOuiService] (Quarkus Main Thread) An error occurred while attempting to update local database: Unexpected response status code from Wire
sharkOuiService: 404. Will try again later.: org.rm3l.macoui.exceptions.MacOuiException: Unexpected response status code from WiresharkOuiService: 404                                         
        at org.rm3l.macoui.services.clients.wireshark.WiresharkOuiService.fetchData(WiresharkOuiService.java:66)                                                                               
        at org.rm3l.macoui.services.clients.wireshark.WiresharkOuiService_ClientProxy.fetchData(Unknown Source)                                                                                
        at org.rm3l.macoui.services.MacOuiService.lambda$scheduleDatabaseUpdate$1(MacOuiService.java:79)                                                                                       
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)                                                                                                 
        at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)                                                                                                
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)                                                                                           
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)                                                                                                     
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)                                                                                                      
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)                                                                                                     
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)                                                                                                           
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223)                                                                                          
        at java.base/java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915)                                                                                                    
        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433)                                                                                                        
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687)                                                                                                           
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)                                                                                               
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)                                                                                         
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)                                                                                                     
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.rm3l.macoui.services.MacOuiService.scheduleDatabaseUpdate(MacOuiService.java:80)
        at org.rm3l.macoui.services.MacOuiService.startup(MacOuiService.java:63)
        at org.rm3l.macoui.services.MacOuiService_Observer_startup_6087e0b5ee09042980a51371105b2198e3aee6cd.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:310)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:78)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

```
$ http GET http://localhost:8080/q/health/live
HTTP/1.1 503 Service Unavailable
content-length: 202
content-type: application/json; charset=UTF-8

{
    "checks": [
        {
            "data": {
                "status_code": 404
            },
            "name": "wireshark",
            "status": "DOWN"
        }
    ],
    "status": "DOWN"
}
```

**Comment by rm3l** [comment]
Per https://gitlab.com/wireshark/wireshark/-/commit/0b5791b08d0e8a4aa49719dcaf98c96f31a6aa48, the Wireshark OUI list is no longer being maintained. Switching to an older tagged version of this list for now, but we should ultimately switch to using the official IEEE OUI list.
